<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>c68a7265-4509-4b83-9c93-4dbbd1b2cdb6</elementGuidId>
    <imagePath></imagePath>
    <name>link_productItems</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[1]/a[9]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'product/${link_productItems_product_id}') and equals(@text,'Thor Hammer
            $11.14')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="${link_productItems_dataTest}"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Thor Hammer
        $11.14</value>
        <webElementGuid>f768743d-c22c-4eef-9b72-ebcf4e60ce3b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>product/${{link_productItems_product_id}}</value>
        <webElementGuid>f768743d-c22c-4eef-9b72-ebcf4e60ce3b</webElementGuid>
    </webElementProperties>
</WebElementEntity>