<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>1f8fbc17-6c77-4641-a0e8-b1c6cb7ad6dc</elementGuidId>
    <imagePath></imagePath>
    <name>link_moreInformation</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-detail[1]/div[2]/div[1]/div[1]/a[2]/div[2]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'#') and equals(@text,'More information')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Open-end Spanners (Set) Open-"i] &gt;&gt; internal:role=link</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>#</value>
        <webElementGuid>748070a6-8d26-474e-949b-d29143c1e332</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>More information</value>
        <webElementGuid>748070a6-8d26-474e-949b-d29143c1e332</webElementGuid>
    </webElementProperties>
</WebElementEntity>