<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>e42bf217-882e-44ce-96d4-5f00acccff36</elementGuidId>
    <imagePath></imagePath>
    <name>link_product01J912Hfethf1T3Xes6H5Bkk98</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-category[1]/div[2]/div[2]/div[1]/a[3]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/01J912HFETHF1T3XES6H5BKK98') and equals(@text,'Bolt Cutters
            $48.41')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="product-01J912HFETHF1T3XES6H5BKK98"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/01J912HFETHF1T3XES6H5BKK98</value>
        <webElementGuid>748070a6-8d26-474e-949b-d29143c1e332</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Bolt Cutters
        $48.41</value>
        <webElementGuid>748070a6-8d26-474e-949b-d29143c1e332</webElementGuid>
    </webElementProperties>
</WebElementEntity>