<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>02b684d6-cfc9-42d6-93de-eda0252f8ddb</elementGuidId>
    <imagePath></imagePath>
    <name>link_SignIn2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/app-header[1]/nav[1]/div[1]/div[1]/ul[1]/li[4]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/auth/login') and equals(@text,'Sign in')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="nav-sign-in"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/auth/login</value>
        <webElementGuid>f768743d-c22c-4eef-9b72-ebcf4e60ce3b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sign in</value>
        <webElementGuid>f768743d-c22c-4eef-9b72-ebcf4e60ce3b</webElementGuid>
    </webElementProperties>
</WebElementEntity>