<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>b5657028-c69d-4548-9f2d-0a03ff0cb5a5</elementGuidId>
    <imagePath></imagePath>
    <name>link_pliersMoreInformation</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-detail[1]/div[2]/div[1]/div[1]/a[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/product/01J912HFEC20J43Z2EMKSQS1T0') and equals(@text,'Pliers
            More information')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Pliers Pliers More information"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/product/01J912HFEC20J43Z2EMKSQS1T0</value>
        <webElementGuid>748070a6-8d26-474e-949b-d29143c1e332</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Pliers
        More information</value>
        <webElementGuid>748070a6-8d26-474e-949b-d29143c1e332</webElementGuid>
    </webElementProperties>
</WebElementEntity>