<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>31102d15-2c21-41d7-af3b-69c889389159</elementGuidId>
    <imagePath></imagePath>
    <name>button_favoritesCartActions</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-detail[1]/div[1]/div[2]/div[2]/button[2]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@id,'btn-add-to-cart') and equals(@text,'Sepete ekle')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>[data-test="${button_favoritesCartActions_dataTest}"]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>id</name>
        <type>Main</type>
        <value>btn-add-to-cart</value>
        <webElementGuid>f768743d-c22c-4eef-9b72-ebcf4e60ce3b</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sepete ekle</value>
        <webElementGuid>f768743d-c22c-4eef-9b72-ebcf4e60ce3b</webElementGuid>
    </webElementProperties>
</WebElementEntity>