<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>f00a5904-9c74-4bbc-9f74-0cbc94079105</elementGuidId>
    <imagePath></imagePath>
    <name>item_nextPage</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/app-root[1]/div[1]/app-overview[1]/div[3]/div[2]/div[2]/app-pagination[1]/nav[1]/ul[1]/li[7]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>li &gt;&gt; internal:has-text="»"i</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>